{{- range $app := .Values.apps }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{$.Release.Name}}-init-{{ $app.name | replace "_" "-" }}-db-{{ $.Values.image.tag }}"
  labels:
    heritage: {{$.Release.Service | quote }}
    release: {{$.Release.Name | quote }}
    chart: "{{$.Chart.Name}}-{{$.Chart.Version}}"
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-install, pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  backoffLimit: 5
  template:
    metadata:
      name: "{{$.Release.Name}}-init-{{ $app.name | replace "_" "-" }}-db"
      labels:
        heritage: {{$.Release.Service | quote }}
        release: {{$.Release.Name | quote }}
        chart: "{{$.Chart.Name}}-{{$.Chart.Version}}"
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      restartPolicy: Never
      initContainers:
      - name: mysql-ready
        image: mysql
        env:
        - name: DB_USER
          value: "root"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "mysql.fullname" $ }}
              key: mysql-root-password
        - name: DB_HOST
          value: "{{ template "mysql.fullname" $ }}.{{ $.Release.Namespace }}.svc.cluster.local"
        - name: DB_PORT
          value: "3306"
        command: ['sh', '-c', 'mysql -w --connect-timeout=5 -s -N -h"${DB_HOST}" -P"${DB_PORT}" -u"${DB_USER}" -p"${DB_PASSWORD}" -e "SELECT USER()"']
      {{- if $.Values.image.pullSecret }}
      imagePullSecrets:
      - name: "{{ $.Values.image.pullSecret }}"
      {{- end }}
      containers:
      - name: post-install-db-setup
        image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag }}"
        imagePullPolicy: {{ $.Values.image.pullPolicy }}
        args: ["dpmcli", "{{ $app.name }}", "buildSchema", "-a", "--debug"]
        securityContext:
          runAsNonRoot: true
        env:
        - name: DB_USER
          value: "root"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "mysql.fullname" $ }}
              key: mysql-root-password
        - name: DB_HOST
          value: "{{ template "mysql.fullname" $ }}.{{ $.Release.Namespace }}.svc.cluster.local"
        - name: DB_PORT
          value: "3306"
        - name: DPM_CONF_DB_URL
          value: "{{ $.Values.influxdb.proto }}://{{ template "influxdb.fullname" $ }}.{{ $.Release.Namespace }}.svc.cluster.local:{{ $.Values.influxdb.config.http.bind_address }}"
        - name: DPM_CONF_DB_NAME
          value: "dpm"
        - name: DPM_CONF_DB_USER
          value: {{ $.Values.schInfluxUser }}
        - name: DPM_CONF_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: "{{ template "fullname" $ }}"
              key: influxdb-password
{{- end }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{.Release.Name}}-influx-setup-user-{{ $.Values.image.tag }}"
  labels:
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  backoffLimit: 5
  template:
    metadata:
      name: "{{.Release.Name}}-influx-setup-user"
      labels:
        heritage: {{.Release.Service | quote }}
        release: {{.Release.Name | quote }}
        chart: "{{.Chart.Name}}-{{.Chart.Version}}"
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      restartPolicy: Never
      containers:
      - name: post-install-influx-setup
        image: appropriate/curl:latest
        imagePullPolicy: IfNotPresent
        args:
          - "/bin/sh"
          - "-c"
          - |
             curl -v -m 10 -X POST {{ .Values.influxdb.proto }}://{{ template "influxdb.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local:8086/query \
             --data-urlencode \
             "q=CREATE USER \"${INFLUXDB_USER}\" WITH PASSWORD '${INFLUXDB_PASSWORD}' WITH ALL PRIVILEGES"
        securityContext:
          runAsNonRoot: true
        env:
        - name: INFLUXDB_USER
          value: {{ .Values.schInfluxUser }}
        - name: INFLUXDB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" . }}
              key: influxdb-password
---
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{.Release.Name}}-influx-setup-db-{{ $.Values.image.tag }}"
  labels:
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "-4"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  backoffLimit: 5
  template:
    metadata:
      name: "{{.Release.Name}}-influx-setup-db"
      labels:
        heritage: {{.Release.Service | quote }}
        release: {{.Release.Name | quote }}
        chart: "{{.Chart.Name}}-{{.Chart.Version}}"
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      restartPolicy: Never
      containers:
      - name: post-install-influx-setup-db
        image: appropriate/curl:latest
        imagePullPolicy: IfNotPresent
        args:
          - "/bin/sh"
          - "-c"
          - |
             curl -v -m 10 -u"${INFLUXDB_USER}:${INFLUXDB_PASSWORD}" -X POST {{ .Values.influxdb.proto }}://{{ template "influxdb.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local:8086/query \
             --data-urlencode \
             "q=CREATE DATABASE ${DB_NAME}"
        securityContext:
          runAsNonRoot: true
        env:
        - name: DB_NAME
          value: dpm
        - name: INFLUXDB_USER
          value: {{ .Values.schInfluxUser }}
        - name: INFLUXDB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" . }}
              key: influxdb-password

---
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{.Release.Name}}-influx-setup-app-db-{{ $.Values.image.tag }}"
  labels:
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "-3"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  backoffLimit: 5
  template:
    metadata:
      name: "{{.Release.Name}}-influx-setup-app-db"
      labels:
        heritage: {{.Release.Service | quote }}
        release: {{.Release.Name | quote }}
        chart: "{{.Chart.Name}}-{{.Chart.Version}}"
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      restartPolicy: Never
      containers:
      - name: post-install-influx-setup-app-db
        image: appropriate/curl:latest
        imagePullPolicy: IfNotPresent
        args:
          - "/bin/sh"
          - "-c"
          - |
             curl -v -m 10 -u"${INFLUXDB_USER}:${INFLUXDB_PASSWORD}" -X POST {{ .Values.influxdb.proto }}://{{ template "influxdb.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local:8086/query \
             --data-urlencode \
             "q=CREATE DATABASE ${DB_NAME}"
        securityContext:
          runAsNonRoot: true
        env:
        - name: DB_NAME
          value: dpm_app
        - name: INFLUXDB_USER
          value: {{ .Values.schInfluxUser }}
        - name: INFLUXDB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" . }}
              key: influxdb-password
---
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{$.Release.Name}}-init-system-id-{{ $.Values.image.tag }}"
  labels:
    heritage: {{$.Release.Service | quote }}
    release: {{$.Release.Name | quote }}
    chart: "{{$.Chart.Name}}-{{$.Chart.Version}}"
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "-4"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  backoffLimit: 5
  template:
    metadata:
      name: "{{$.Release.Name}}-init-system-id"
      labels:
        heritage: {{$.Release.Service | quote }}
        release: {{$.Release.Name | quote }}
        chart: "{{$.Chart.Name}}-{{$.Chart.Version}}"
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      restartPolicy: Never
      initContainers:
      - name: mysql-ready
        image: mysql
        env:
        - name: DB_USER
          value: "root"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "mysql.fullname" $ }}
              key: mysql-root-password
        - name: DB_HOST
          value: "{{ template "mysql.fullname" $ }}.{{ $.Release.Namespace }}.svc.cluster.local"
        - name: DB_PORT
          value: "3306"
        command: ['sh', '-c', 'mysql -w --connect-timeout=5 -s -N -h"${DB_HOST}" -P"${DB_PORT}" -u"${DB_USER}" -p"${DB_PASSWORD}" -e "SELECT USER()"']
      {{- if $.Values.image.pullSecret }}
      imagePullSecrets:
      - name: "{{ $.Values.image.pullSecret }}"
      {{- end }}
      containers:
      - name: post-install-db-setup
        image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag }}"
        imagePullPolicy: {{ $.Values.image.pullPolicy }}
        {{- if $.Values.image.dev }}
        args: ["dpmcli", "security", "activationKey", "--dev"]
        {{ else }}
        args: ["dpmcli", "security", "systemId", "-c"]
        {{- end }}
        securityContext:
          runAsNonRoot: true
        env:
        - name: DPM_CONF_APPS_TO_START
          value: "security"
        - name: DB_USER
          value: "root"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "mysql.fullname" $ }}
              key: mysql-root-password
        - name: DB_HOST
          value: "{{ template "mysql.fullname" $ }}.{{ $.Release.Namespace }}.svc.cluster.local"
        - name: DB_PORT
          value: "3306"